---

- hosts: ansible-server

  tasks:
  - name: create docker image
    command: docker build -t regapp:latest .
    args:
      chdir: /opt/docker

  - name: create tag to push image onto docker hub
    command: docker tag regapp:latest sehindemitech/regapp:latest

  - name: push docker image
    command: docker push sehindemitech/regapp:latest

